### ISSUE TITLE
filenames should be shorter

### ISSUE THREAD

**Issue by RudoRoemer** [DisQS/MachineLearning-Percolation#11]
I just ran

for dir in p0*; do echo $dir; cd $dir; rename 'n_clus' 'nc' *; rename 'size_max_clus' 'smc' *; rename '_data_pkl' '' *; rename '_info' '' *; rename '_im_lattice' '' *; cd ..; done

in L10 and now the filenames for all .pkl, .txt and .png files are something such as 

pc_0_0_0_0_0__p0.55_L10_s3105819178_nc3_smc53_n3.png 

that is, they are all the same, shorter format in the name, but use different type (.pkl, .txt, .png). I noticed that some names have the "_n##" before the "." while others don't. Why? Please explain before I run this conversion of the L100/L200 data. Thanks.

**Comment by RudoRoemer** [comment]
There is a related issue: some filenames are

/storage/disqs/ML-Percolation/Data/L100/p0.1/pc_0_0_0_0_0__p0.1_L100_s3_nc822_smc5_n822.png

while other are

/storage/disqs/ML-Percolation/Data/L100/p0.1/pc_0_0_0_0_0__p0.1_L100_s5nc805_smc6_n805.png

i.e. sometime there is a "_" before the "nc" and sometime not. This should be consistenly "_nc",

**Comment by Djenabou** [comment]
I went back into perco_generate_data.py and fixed the naming of the data for future data generation. It should be noted that nc = n and therefore the missing n# can be easily filled.
